name: Nirmal Khedkar
title: Nirmal Khedkar
email: nirmalhk7@gmail.com
plugins:
  - jekyll-paginate
  - jekyll-sitemap
blog: Spaceride

paginate: 6
paginate_path: "/blog/page:num/"
collections:
  projects:
    output: true
algolia:
  application_id: 'RASJLX7IX5'
  index_name: 'prod_name'
  files_to_exclude: []