- name: LinkedIn
  url: https://www.linkedin.com/in/nirmalhk7/
- name: GitHub
  url: https://www.github.com/nirmalhk7
- name: Goodreads
  url: https://www.goodreads.com/user/show/93069537-nirmal
- name: RSS
  url: /feed.xml
- name: Email
  url: mailto:nirmalhk7@gmail.com