name: Jest UI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Run Jest tests
      run: npm test
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jest-junit-report
        path: reports/jest-junit.xml
        retention-days: 14
